# Generated by Django 4.0.2 on 2025-07-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_race_name_alter_skill_bonus_alter_skill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
